### ISSUE TITLE
Schema data structure

### ISSUE THREAD

**Issue by jaloisi834** [jaloisi834/go-json-schema-generator#1]
# Summary

At the center of this service will be the data structure representing a JSON schema. We need to decide which keywords will be necessary to create basic schemas and design a data structure for them.

I can think of two viable options at the moment:

Description | Pros | Cons
-- | -- | --
A model for each value of type | Prevents type conflicts, optimizes merging/copying | Requires reflection, risk of repeated code across models
A single, one size fits all model | Doesn't require reflection | Risk of type conflicts, adds overhead to merging/copying

# To-Do

- [x] Review each keyword's purpose and usage ([JSON Schema Validation](https://datatracker.ietf.org/doc/draft-handrews-json-schema-validation/))
- [x] Decide which keywords will be implemented for v1.0.0
- [x] Design Schema data structure
- [x] Build Schema data structure
